name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env: 
  GitHubPackageFeedUrl: https://nuget.pkg.github.com/Changwon-Lee-Cloocus/index.json
  LogicProjectPath: ${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.CREDENTIAL }}
    - name: Azure key vault - Get Secrets
      uses: Azure/get-keyvault-secrets@v1.2
      with:
        # Name of the azure key vault
        keyvault: hackerthoncwon
        # Name of the secret to be fetched
        secrets: globalPassword
      id: myGetSecretAction
    - name: Azure App Service Settings
      uses: Azure/appservice-settings@v1
      with:
        # Name of the Azure Web App
        app-name: hackerthon
        mask-inputs: false
        # Name of an existing slot other than the production slot. Default value is production
        app-settings-json: '[{"name":"SimulatedFailureChance", "value": "0"}, {"name": "GlobalPassword", "value": ${{steps.myGetSecretAction.outputs.globalPassword}}}]'
    - run: echo "The webapp-url is ${{ steps.settings.outputs.webapp-url }}"
      
