name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    
env: 
  GitHubPackageFeedUrl: https://nuget.pkg.github.com/Changwon-Lee-Cloocus/index.json
  LogicProjectPath: ${{ github.WORKSPACE }}/AnimalAdoption.Common.Logic

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.CREDENTIAL }}
    - name: Azure App Service Settings
      uses: Azure/appservice-settings@v1
      with:
        # Name of the Azure Web App
        app-name: hackerthon
        mask-inputs: false
        # Name of an existing slot other than the production slot. Default value is production
        app-settings-json: ${{ secrets.APP_SETTINGS }}
    - run: echo "The webapp-url is ${{ steps.settings.outputs.webapp-url }}"
      
